# IMAPX200 Platform Support
snd-soc-imapx200-objs := imapx200-pcm.o
obj-$(CONFIG_SND_IMAPX_SOC) += snd-soc-imapx200.o

snd-soc-imapx200-wm8987-objs := imapx200_wm8987.o
obj-$(CONFIG_SND_IMAPX200_SOC_IMAPX200_WM8987) += snd-soc-imapx200-wm8987.o

snd-soc-imapx200-es8388-objs := imapx200_es8388.o
obj-$(CONFIG_SND_IMAPX200_SOC_IMAPX200_ES8388) += snd-soc-imapx200-es8388.o

# IMAPX200 CPU Support 
snd-soc-imapx200-ac97-objs := imapx200-ac97.o
#obj-$(CONFIG_SND_IMAPX_SOC) += snd-soc-imapx200.o
obj-$(CONFIG_SND_IMAPX200_SOC_AC97) += snd-soc-imapx200-ac97.o

snd-soc-imapx200-i2s-objs := imapx200-i2s.o
#obj-$(CONFIG_SND_IMAPX_SOC) += snd-soc-imapx200.o
obj-$(CONFIG_SND_IMAPX200_SOC_I2S) += snd-soc-imapx200-i2s.o


# IMAPX200 Machine Support
#snd-soc-smdk6400-wm8987-objs := smdk6400_wm8987.o
snd-soc-imapx200-lm4550-objs := imapx200_lm4550.o
obj-$(CONFIG_SND_IMAPX200_SOC_IMAPX200_LM4550) += snd-soc-imapx200-lm4550.o

