#
# Makefile of memalloc.
#
# Sololz <sololz.luo@gmail.com>.
#

obj-$(CONFIG_IMAP_MEMALLOC) += memalloc.bin
obj-$(CONFIG_IMAP_SHARED_MEMORY_SUPPORT) += shm_so.bin
obj-$(CONFIG_IMAP_MPMEM_MANAGEMENT_SUPPORT) += mp_mem.bin
obj-$(CONFIG_MEMORY_ALLOCATOR_WITH_NO_EXT_FRAGMENT) += mmalcr.bin
