#!/system/bin/busybox sh
/system/bin/busybox insmod /system/lib/modules/galcore.ko registerMemBase=0x20f00000 irqLine=54 contiguousSize=0x1400000
/system/bin/busybox mknod /dev/galcore c 199 0
chmod 777 /dev/graphics/fb0
chmod 777 /dev/galcore

##	/system/bin/busybox mkfs.vfat /dev/block/mtdblock2
##	/system/bin/busybox touch /data/mkfs_vfat.txt

## busybox mkswap /dev/block/mtdblock3
## busybox swapon /dev/block/mtdblock3



/system/bin/busybox insmod /system/lib/modules/permfd.ko
chmod 777 /dev/permfd

