#
## Makefile for the HDMI output interface driver
#

ifeq ($(CONFIG_HDMI_OUTPUT_SUPPORT),y)
obj-y                                   += imap_HDMI.o
obj-y                                   += EP932api.o
obj-y                                   += EP932Controller.o
obj-y                                   += DDC_If.o
obj-y                                   += Edid.o
obj-y                                   += EP932_If.o
obj-y                                   += EP932SettingsData.o
obj-y                                   += HDCP.o
endif

