#
#Makefile for linux kernel
#
#


#IMAPX200 support files

obj-$(CONFIG_CPU_IMAPX200)		+= irq.o clock.o time.o devices.o pwm.o




#imdkx200 machine specific support
obj-$(CONFIG_MACH_IMAPX200)		+=cpu.o 
