
#obj-$(CONFIG_IMAP_ENCODE) += imapx200_cam.o
obj-$(CONFIG_IMAP_ENCODE) += ima_cam.o
obj-$(CONFIG_OV2655) += ovxxxx.o
obj-$(CONFIG_OV7670) += ovxxxx.o
obj-$(CONFIG_OV9650) += ovxxxx.o
obj-$(CONFIG_IMAP_ENCODE) += bf3603.o
obj-$(CONFIG_IMAP_ENCODE) += hy511.o
obj-$(CONFIG_IMAP_ENCODE) += gc0308.o
obj-$(CONFIG_IMAP_ENCODE) += gc0307.o

EXTRA_CFLAGS += -DLINUX
EXTRA_CFLAGS += -DDIVX_ENABLE



